### ISSUE TITLE
mukhyala's todo list

### ISSUE THREAD

**Issue by mukhyala** [githubteacher/dev-nov-02#20]
- [x] Create an issue
- [x] Create a Branch
- [x] Create a Pull Request
- [x] Merge a PR
- [ ] Have a good time?

👍
