### ISSUE TITLE
pacificajoe's todo list

### ISSUE THREAD

**Issue by PacificaJoe** [githubteacher/dev-nov-02#4]
- [X] Create an Issue
- [ ] Create a branch
- [ ] Create a Pull request
- [ ] Meeeerge a PR
- [ ] Have a good time!

🐐 baaaah
